name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  get-next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@0cdefe1224944c23645e5131f7a5189672c0df92 # v4

  build-artifacts:
    name: Build ${{ matrix.name }} artifacts
    needs: get-next-version
    if: needs.get-next-version.outputs.new-release-published == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            label: linux
            os: ubuntu-24.04
            artifact_glob: floki-*.tar.gz
            rpm: true
          - name: macOS
            label: macos
            os: macos-latest
            artifact_glob: floki-*.zip
            rpm: false
    uses: ./.github/workflows/build-artifacts.yml
    with:
      runner: ${{ matrix.os }}
      toolchain: stable
      artifact_glob: ${{ matrix.artifact_glob }}
      artifact_name: dist-${{ matrix.label }}
      upload_artifact: true
      run_tests: false
      rpm: ${{ matrix.rpm }}
      release_version: ${{ needs.get-next-version.outputs.new-release-version }}
      fetch_depth: '0'

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - get-next-version
      - build-artifacts
    if: needs.get-next-version.outputs.new-release-published == 'true'
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1

      - name: Install semantic-release-cargo
        run: cargo install --locked semantic-release-cargo

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: "node"

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist

      - name: Generate checksums
        run: |
          cd dist
          for file in *; do
            if [ "$file" = "SHA256SUMS.txt" ]; then
              continue
            fi
            shasum -a 256 "$file"
          done > SHA256SUMS.txt

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.PUBLISH_SECRET }}
